# -----------------------------------------------------------------------------
net:
  depth:
    enc_name: 'convnext_base'
# -----------------------------------------------------------------------------
